# import os
# import xacro  # הוספנו את הספרייה הזו כדי לעקוף את באג ה-Parser
# from ament_index_python.packages import get_package_share_directory
# from launch import LaunchDescription
# from launch.actions import SetEnvironmentVariable, TimerAction, ExecuteProcess
# from launch.substitutions import PathJoinSubstitution, EnvironmentVariable
# from launch_ros.substitutions import FindPackageShare
# from launch_ros.actions import Node

# def generate_launch_description():
#     pkg_share = FindPackageShare('robot_description')
#     pkg_dir = get_package_share_directory('robot_description')

#     world = PathJoinSubstitution([pkg_share, 'world', 'maze', 'maze.world'])
#     robot_description_path = os.path.join(pkg_dir, 'world', 'robot', 'robot.urdf.xacro')

#     # --- התיקון הקריטי: עיבוד ה-XML ישירות בפייתון והפיכתו למחרוזת חסינה ---
#     doc = xacro.process_file(robot_description_path)
#     robot_description_xml = doc.toxml()

#     set_model_path = SetEnvironmentVariable(
#         name='GAZEBO_MODEL_PATH',
#         value=[PathJoinSubstitution([pkg_share, 'world']), ':', EnvironmentVariable('GAZEBO_MODEL_PATH', default_value='')]
#     )

#     cleanup_gazebo = ExecuteProcess(
#         cmd=['bash', '-c', 'pkill -x gzserver || true; pkill -x gzclient || true; sleep 0.2; true'],
#         output='screen'
#     )

#     gzserver = ExecuteProcess(
#         cmd=['gzserver', world, '--verbose',
#              '-s', 'libgazebo_ros_init.so', '-s', 'libgazebo_ros_factory.so'],
#         output='screen'
#     )

#     gzclient = ExecuteProcess(
#         cmd=['gzclient'],
#         output='screen'
#     )

#     rsp = Node(
#         package='robot_state_publisher',
#         executable='robot_state_publisher',
#         name='robot_state_publisher',
#         output='screen',
#         parameters=[{'use_sim_time': True, 'robot_description': robot_description_xml}]
#     )

#     spawn_robot = Node(
#         package='gazebo_ros',
#         executable='spawn_entity.py',
#         arguments=['-entity', 'robot1', '-topic', 'robot_description',
#                    '-x', '-1', '-y', '0', '-z', '1'],
#         output='screen'
#     )

#     return LaunchDescription([
#         SetEnvironmentVariable(name='RCL_ARGS', value=''),
#         SetEnvironmentVariable(name='ROS_ARGUMENTS', value=''),
#         set_model_path,
#         cleanup_gazebo,
#         TimerAction(period=0.5, actions=[gzserver]),
#         TimerAction(period=1.0, actions=[gzclient]),
#         rsp,
#         TimerAction(period=2.0, actions=[spawn_robot]),
#     ])

import os
import re
import xacro
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import SetEnvironmentVariable, TimerAction, ExecuteProcess, RegisterEventHandler
from launch.event_handlers import OnProcessExit
from launch.substitutions import PathJoinSubstitution, EnvironmentVariable
from launch_ros.substitutions import FindPackageShare
from launch_ros.actions import Node

def generate_launch_description():
    pkg_share = FindPackageShare('robot_description')
    pkg_dir = get_package_share_directory('robot_description')

    world = PathJoinSubstitution([pkg_share, 'world', 'maze', 'maze.world'])
    robot_description_path = os.path.join(pkg_dir, 'world', 'robot', 'robot.urdf.xacro')

    doc = xacro.process_file(robot_description_path)
    robot_description_xml = doc.toxml()
    # gazebo_ros2_control re-fetches robot_description from robot_state_publisher and
    # forwards it to its embedded controller_manager node as a "--param name:=value"
    # CLI-style override. xacro's autogenerated header comment uses "|" as an ASCII-art
    # border, which that override parser misreads as a YAML block-scalar indicator and
    # fails on ("Couldn't parse parameter override rule"). Strip all comments to avoid it.
    robot_description_xml = re.sub(r'<!--.*?-->', '', robot_description_xml, flags=re.DOTALL)

    set_model_path = SetEnvironmentVariable(
        name='GAZEBO_MODEL_PATH',
        value=[PathJoinSubstitution([pkg_share, 'world']), ':', EnvironmentVariable('GAZEBO_MODEL_PATH', default_value='')]
    )

    cleanup_gazebo = ExecuteProcess(
        cmd=['bash', '-c', 'pkill -x gzserver || true; pkill -x gzclient || true; sleep 0.2; true'],
        output='screen'
    )

    gzserver = ExecuteProcess(
        cmd=['gzserver', world, '--verbose',
             '-s', 'libgazebo_ros_init.so', '-s', 'libgazebo_ros_factory.so'],
        output='screen'
    )

    gzclient = ExecuteProcess(
        cmd=['gzclient'],
        output='screen'
    )

    rsp = Node(
        package='robot_state_publisher',
        executable='robot_state_publisher',
        name='robot_state_publisher',
        output='screen',
        parameters=[{'use_sim_time': True, 'robot_description': robot_description_xml}]
    )

    spawn_robot = Node(
        package='gazebo_ros',
        executable='spawn_entity.py',
        # User-confirmed clear spot (picked live via RViz "2D Goal Pose",
        # converted from the slam map frame to Gazebo world coordinates).
        # Resets to known-open ground after the robot got wedged near a
        # wall while we were debugging why it wasn't driving there.
        arguments=['-entity', 'robot1', '-topic', 'robot_description',
                   '-x', '1.78', '-y', '1.44', '-z', '1'],
        output='screen'
    )

    robot_controller = Node(
        package='robot_description',
        executable='TwistToAckermann',
        name='robot_controller',
        output='screen',
        parameters=[{'use_sim_time': True}]
    )

    # --- חזרנו למקור: מגדירים במפורש את נתיבי הקבצים ---
    jsb_yaml = os.path.join(pkg_dir, 'config', 'joint_state_broadcaster.yaml')
    ackermann_yaml = os.path.join(pkg_dir, 'config', 'ackermann_steering_controller.yaml')

    # --- הבקרים מקבלים את קבצי התצורה שלהם ישירות ---
    joint_state_broadcaster = Node(
        package='controller_manager', executable='spawner', output='screen',
        arguments=['joint_state_broadcaster', '--controller-manager', '/controller_manager', '--param-file', jsb_yaml],
    )

    ackermann_steering_controller = Node(
        package='controller_manager', executable='spawner', output='screen',
        arguments=['ackermann_steering_controller', '--controller-manager', '/controller_manager', '--param-file', ackermann_yaml],
    )

    spawn_jsb = RegisterEventHandler(
        OnProcessExit(target_action=spawn_robot, on_exit=[joint_state_broadcaster])
    )
    spawn_ack = RegisterEventHandler(
        OnProcessExit(target_action=joint_state_broadcaster, on_exit=[ackermann_steering_controller])
    )

    return LaunchDescription([
        SetEnvironmentVariable(name='RCL_ARGS', value=''),
        SetEnvironmentVariable(name='ROS_ARGUMENTS', value=''),
        set_model_path,
        cleanup_gazebo,
        TimerAction(period=0.5, actions=[gzserver]),
        TimerAction(period=1.0, actions=[gzclient]),
        rsp,
        TimerAction(period=2.0, actions=[spawn_robot]),
        robot_controller,
        spawn_jsb,
        spawn_ack,
    ])