services:
  overhead_tracker:
    build: .
    container_name: overhead_tracker
    network_mode: host
    
    # 1. Pass display variable to container
    environment:
      - DISPLAY=${DISPLAY}
      
    volumes:
      - .:/app
      # 2. Connect to host X11 display engine
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      
    # 3. Mount host USB camera
    devices:
      - /dev/video0:/dev/video0
