services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    network_mode: "host"
    privileged: true
    volumes:
      - ./ts-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped
