version: '3.8'
services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    privileged: true
    network_mode: "host"
    volumes:
      - ./ts-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    environment:
      - TS_AUTHKEY=tskey-auth-kDQuVvyKZA11CNTRL-e7hZfXzZzfbvewGFs7pNgbdpEQzeNxMc
      - TS_EXTRA_ARGS=--accept-dns=false
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_HOSTNAME=itay-rpi
      - TS_USERSPACE=false
    restart: unless-stopped
