# ==========================================
# 1. AGENT CONFIGURATION
# ==========================================
[agent]
  interval = "5s"
  round_interval = true
  metric_buffer_limit = 10000
  debug = true
  hostname = "remote_pc"

# ==========================================
# 2. OUTPUTS (Routing to 2 different buckets)
# ==========================================

# --- Output 1: Send ONLY ROS2 data to "sensors" bucket ---
[[outputs.influxdb_v2]]
  urls = ["http://127.0.0.1:8181"]
  # token = "apiv3_CL-NZqu4HRpOYR7ENJmN3kwgRXCaFpNEEC_j0QHrBqwaMf-XKoFfWWbUq9Oh83xQKEZNGNI9PO44UPPTtr6OKQ"
  token = "apiv3_rf3is-glYXXvddTlNCT8Yen711BFDx5nb0o_a68lWoLb13-q530Cs1QVIuvUBU9IfhCe43qaud8LlAKgx4hZFQ"
  organization = "Robot"
  bucket = "sensors"
  
  # CORRECTED SYNTAX: Define tagpass as a sub-section
  [outputs.influxdb_v2.tagpass]
    source = ["ros2_bridge"]

# ==========================================
# 3. INPUTS (Receive data from ROS2 bridge)
# ==========================================

[[inputs.socket_listener]]
  service_address = "unix:///tmp/sockets/telegraf.sock"
  data_format = "influx"

  [inputs.socket_listener.tags]
    source = "ros2_bridge"


