# planner_server:
#   ros__parameters:
#     use_sim_time: true
#     planner_plugins: ["GridBased"]
#     GridBased:
#       plugin: "nav2_smac_planner/SmacPlannerHybrid"
#       tolerance: 0.2
#       allow_unknown: true
#       cost_travel_multiplier: 2.0
#       max_planning_time: 3.0

# # Controller server tuned for an Ackermann vehicle using the MPPI controller.
# controller_server:
#   ros__parameters:
#     use_sim_time: true
#     controller_frequency: 20.0
#     costmap_update_timeout: 0.3
#     min_x_velocity_threshold: 0.001
#     min_y_velocity_threshold: 0.001
#     min_theta_velocity_threshold: 0.001
#     failure_tolerance: 0.3
#     odom_topic: "odom"
#     odom_duration: 0.3
#     controller_plugins: ["FollowPath"]

#     FollowPath:
#       plugin: "nav2_mppi_controller::MPPIController"
#       motion_model: "Ackermann"
#       AckermannConstraints:
#         min_turning_r: 0.1
#       model_dt: 0.05
#       time_steps: 40        # 2 s horizon at 20 Hz
#       batch_size: 1500
#       vx_max: 1.0
#       vx_min: -1.0
#       vy_max: 0.0
#       vy_min: 0.0
#       wz_max: 2.0
#       temperature: 0.3
#       gamma: 0.015
#       visualize: false
#       publish_optimal_trajectory: true
#       publish_critics_stats: true
#       enforce_path_inversion: false
#       enable_stamped_cmd_vel: true
#       prune_distance: 1.7
#       critics:
#         - "ConstraintCritic"
#         - "CostCritic"
#         - "GoalCritic"
#         - "GoalAngleCritic"
#         - "PathAlignCritic"
#         - "PathFollowCritic"
#         - "PathAngleCritic"
#         - "PreferForwardCritic"
#       ConstraintCritic:
#         enabled: true
#         cost_power: 1
#         cost_weight: 4.0
#       GoalCritic:
#         enabled: true
#         cost_power: 1
#         cost_weight: 5.0
#         threshold_to_consider: 1.4
#       GoalAngleCritic:
#         enabled: true
#         cost_power: 1
#         cost_weight: 3.0
#         threshold_to_consider: 0.5
#       PreferForwardCritic:
#         enabled: true
#         cost_power: 1
#         cost_weight: 5.0
#         threshold_to_consider: 0.5
#       CostCritic:
#         enabled: true
#         cost_power: 1
#         cost_weight: 3.81
#         critical_cost: 300.0
#         consider_footprint: true
#         collision_cost: 1000000.0
#         near_goal_distance: 1.0
#         trajectory_point_step: 2
#       PathAlignCritic:
#         enabled: true
#         cost_power: 1
#         cost_weight: 14.0
#         max_path_occupancy_ratio: 0.05
#         trajectory_point_step: 4
#         threshold_to_consider: 0.5
#         offset_from_furthest: 20
#         use_path_orientations: false
#       PathFollowCritic:
#         enabled: true
#         cost_power: 1
#         cost_weight: 5.0
#         offset_from_furthest: 5
#         threshold_to_consider: 1.4
#       PathAngleCritic:
#         enabled: true
#         cost_power: 1
#         cost_weight: 2.0
#         offset_from_furthest: 4
#         threshold_to_consider: 0.5
#         max_angle_to_furthest: 1.0
#         mode: 0

#     progress_checker_plugins: ["progress_checker"]
#     progress_checker:
#       plugin: "nav2_controller::SimpleProgressChecker"
#       required_movement_radius: 0.05
#       movement_time_allowance: 1.0

#     goal_checker_plugins: ["goal_checker"]
#     goal_checker:
#       plugin: "nav2_controller::SimpleGoalChecker"
#       xy_goal_tolerance: 0.25
#       yaw_goal_tolerance: 0.15
#       stateful: false

# smoother_server:
#   ros__parameters:
#     use_sim_time: true
#     smoother_plugins: ["Simple"]
#     Simple:
#       plugin: "nav2_smoother::SimpleSmoother"
#       tolerance: 0.1
#       w_smooth: 0.3
#       w_data: 0.2
#       do_refinement: false

# bt_navigator:
#   ros__parameters:
#     default_bt_xml_filename: "/opt/ros/humble/share/nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml"
#     default_nav_through_poses_bt_xml: "/opt/ros/humble/share/nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml"

# behavior_server:
#   ros__parameters:
#     enable_stamped_cmd_vel: true
#     behavior_plugins: ["backup", "wait"]
#     backup:
#       plugin: "nav2_behaviors/BackUp"
#     wait:
#       plugin: "nav2_behaviors/Wait"

# global_costmap:
#   global_costmap:
#     ros__parameters:
#       use_sim_time: true
#       global_frame: map
#       robot_base_frame: base_link
#       rolling_window: true
#       width: 20
#       height: 20
#       resolution: 0.05
#       footprint: "[ [0.18, 0.18], [0.18, -0.18], [-0.18, -0.18], [-0.18, 0.18] ]"
#       plugins: ["static_layer", "inflation_layer"]
#       static_layer:
#         plugin: "nav2_costmap_2d::StaticLayer"  
#         footprint_clearing_enabled: true
#         restore_cleared_footprint: true 
#       inflation_layer:
#         plugin: "nav2_costmap_2d::InflationLayer"
#         footprint_clearing_enabled: true
#         inflation_radius: 0.05
#         cost_scaling_factor: 6.0
#       update_frequency: 30.0
#       publish_frequency: 30.0

# local_costmap:
#   local_costmap:
#     ros__parameters:
#       use_sim_time: true
#       global_frame: odom
#       robot_base_frame: base_link
#       rolling_window: true
#       width: 5
#       height: 5
#       resolution: 0.05
#       footprint: "[ [0.18, 0.18], [0.18, -0.18], [-0.18, -0.18], [-0.18, 0.18] ]"
#       plugins: ["obstacle_layer", "inflation_layer"]
#       obstacle_layer:
#         plugin: "nav2_costmap_2d::ObstacleLayer"
#         footprint_clearing_enabled: true
#         observation_sources: "scan"
#         scan:
#           topic: /scan
#           data_type: "LaserScan"
#           clearing: true
#           marking: true
#           max_obstacle_height: 2.0
#       inflation_layer:
#         plugin: "nav2_costmap_2d::InflationLayer"
#         footprint_clearing_enabled: true
#         inflation_radius: 0.05
#         cost_scaling_factor: 6.0

# velocity_smoother:
#   ros__parameters:
#     use_sim_time: true
#     enable_stamped_cmd_vel: true
#     smoothing_frequency: 20.0
#     scale_velocities: true
#     feedback: "OPEN_LOOP"
#     odom_topic: "odom"
#     max_velocity: [2.0, 2.0, 3.5]
#     max_accel:    [2.5, 2.0, 4.0]
#     max_decel:    [-2.5, -2.0, -4.0]

# slam_toolbox:
#   ros__parameters:
#     laser_min_range: 0.15
#     laser_max_range: 15.0
#     occupancy_threshold: 0.1
    

# lifecycle_manager_navigation:
#   ros__parameters:
#     use_sim_time: true
#     autostart: true
#     node_names:
#       - slam_toolbox
#       - planner_server
#       - controller_server
#       - behavior_server
#       - smoother_server
#       - bt_navigator
#       - global_costmap
#       - local_costmap
#       - velocity_smoother
#       - waypoint_follower


# amcl:
#   ros__parameters:
#     use_sim_time: True
#     alpha1: 0.2
#     alpha2: 0.2
#     alpha3: 0.2
#     alpha4: 0.2
#     alpha5: 0.2
#     base_frame_id: "base_footprint"
#     beam_skip_distance: 0.5
#     beam_skip_error_threshold: 0.9
#     beam_skip_threshold: 0.3
#     do_beamskip: false
#     global_frame_id: "map"
#     lambda_short: 0.1
#     laser_likelihood_max_dist: 2.0
#     laser_max_range: 100.0
#     laser_min_range: -1.0
#     laser_model_type: "likelihood_field"
#     max_beams: 60
#     max_particles: 2000
#     min_particles: 500
#     odom_frame_id: "odom"
#     pf_err: 0.05
#     pf_z: 0.99
#     recovery_alpha_fast: 0.0
#     recovery_alpha_slow: 0.0
#     resample_interval: 1
#     robot_model_type: "nav2_amcl::DifferentialMotionModel"
#     save_pose_rate: 0.5
#     sigma_hit: 0.2
#     tf_broadcast: true
#     transform_tolerance: 1.0
#     update_min_a: 0.2
#     update_min_d: 0.25
#     z_hit: 0.5
#     z_max: 0.05
#     z_rand: 0.5
#     z_short: 0.05
#     scan_topic: scan


#############################################
#              SLAM TOOLBOX
#############################################
# slam_toolbox:
#   ros__parameters:

#     base_frame: "base_link"
#     odom_frame: "odom"
#     map_frame: "map"

#     scan_topic: "scan"
#     mode: "mapping"
#     use_sim_time: true

#     resolution: 0.05
#     map_update_interval: 2.0

#     min_laser_range: 0.15
#     max_laser_range: 15.0

#     throttle_scans: 1
#     scan_queue_size: 1000

#     use_scan_matching: true
#     use_scan_barycenter: true

#     minimum_travel_distance: 0.1
#     minimum_travel_heading: 0.1

#     do_loop_closing: true
#     loop_search_maximum_distance: 3.0

#     solver_plugin: "solver_plugins::CeresSolver"
#     ceres_linear_solver: "SPARSE_NORMAL_CHOLESKY"
#     ceres_preconditioner: "JACOBI"
#     ceres_trust_strategy: "LEVENBERG_MARQUARDT"
#     ceres_dogleg_type: "TRADITIONAL_DOGLEG"

#     use_map_saver: true
#     map_file_name: "my_map"


#############################################
#              BT NAVIGATOR
#############################################
bt_navigator:
  ros__parameters:
    use_sim_time: True
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odometry/filtered
    bt_loop_duration: 10
    default_server_timeout: 20
    wait_for_service_timeout: 1000
    default_bt_xml_filename: "/opt/ros/humble/share/nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml"
    default_nav_through_poses_bt_xml: "/opt/ros/humble/share/nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml"

    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_compute_path_through_poses_action_bt_node
      - nav2_smooth_path_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_assisted_teleop_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_drive_on_heading_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_globally_updated_goal_condition_bt_node
      - nav2_is_path_valid_condition_bt_node
      - nav2_initial_pose_received_condition_bt_node
      - nav2_reinitialize_global_localization_service_bt_node
      - nav2_rate_controller_bt_node
      - nav2_distance_controller_bt_node
      - nav2_speed_controller_bt_node
      - nav2_truncate_path_action_bt_node
      - nav2_truncate_path_local_action_bt_node
      - nav2_goal_updater_node_bt_node
      - nav2_recovery_node_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_round_robin_node_bt_node
      - nav2_transform_available_condition_bt_node
      - nav2_time_expired_condition_bt_node
      - nav2_path_expiring_timer_condition
      - nav2_distance_traveled_condition_bt_node
      - nav2_single_trigger_bt_node
      - nav2_goal_updated_controller_bt_node
      - nav2_is_battery_low_condition_bt_node
      - nav2_navigate_through_poses_action_bt_node
      - nav2_navigate_to_pose_action_bt_node
      - nav2_remove_passed_goals_action_bt_node
      - nav2_planner_selector_bt_node
      - nav2_controller_selector_bt_node
      - nav2_goal_checker_selector_bt_node
      - nav2_controller_cancel_bt_node
      - nav2_path_longer_on_approach_bt_node
      - nav2_wait_cancel_bt_node
      - nav2_spin_cancel_bt_node
      - nav2_back_up_cancel_bt_node
      - nav2_assisted_teleop_cancel_bt_node
      - nav2_drive_on_heading_cancel_bt_node
      - nav2_is_battery_charging_condition_bt_node

bt_navigator_navigate_to_pose_rclcpp_node:
  ros__parameters:
    use_sim_time: True

bt_navigator_navigate_through_poses_rclcpp_node:
  ros__parameters:
    use_sim_time: True


#############################################
#              PLANNER SERVER (SMAC)
#############################################
planner_server:
  ros__parameters:
    use_sim_time: True
    expected_planner_frequency: 20.0
    planner_plugins: ["GridBased"]

    GridBased:
      plugin: "nav2_smac_planner/SmacPlannerHybrid"
      tolerance: 0.2
      allow_unknown: true
      max_planning_time: 3.0
      motion_model_for_search: "REEDS_SHEPP" 
      minimum_turning_radius: 0.40 
      reverse_penalty: 1.2


#############################################
#           CONTROLLER SERVER (MPPI)
#############################################
controller_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    odom_topic: "/odometry/filtered"
    odom_duration: 0.3
    
    progress_checker_plugins: ["progress_checker"]
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.05
      movement_time_allowance: 1.0

    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"
      motion_model: "Ackermann"

      AckermannConstraints:
        min_turning_r: 0.3

      model_dt: 0.05
      time_steps: 40
      batch_size: 1500

      vx_max: 1.0
      vx_min: -1.0
      vy_max: 0.0
      vy_min: 0.0
      wz_max: 2.0

      temperature: 0.3
      gamma: 0.015
      visualize: false
      publish_optimal_trajectory: true
      publish_critics_stats: true
      enforce_path_inversion: true
      enable_stamped_cmd_vel: true
      prune_distance: 1.0

      critics:
        - "ConstraintCritic"
        - "CostCritic"
        - "GoalCritic"
        - "GoalAngleCritic"
        - "PathAlignCritic"
        - "PathFollowCritic"
        - "PathAngleCritic"
        - "PreferForwardCritic"

      ConstraintCritic:
        enabled: true
        cost_power: 1
        cost_weight: 4.0

      CostCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.81
        critical_cost: 300.0
        consider_footprint: true
        collision_cost: 1000000.0
        near_goal_distance: 1.0
        trajectory_point_step: 2

      GoalCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        threshold_to_consider: 1.4

      GoalAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.0
        threshold_to_consider: 0.5

      PreferForwardCritic:
        enabled: false
        cost_power: 1
        cost_weight: 1.0
        threshold_to_consider: 0.5

      PathAlignCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        max_path_occupancy_ratio: 0.05
        trajectory_point_step: 4
        threshold_to_consider: 0.5
        offset_from_furthest: 20
        use_path_orientations: false

      PathFollowCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        offset_from_furthest: 5
        threshold_to_consider: 1.4

      PathAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 1.0
        offset_from_furthest: 4
        threshold_to_consider: 0.5
        max_angle_to_furthest: 1.0
        mode: 1


#############################################
#               SMOOTHER SERVER
#############################################
smoother_server:
  ros__parameters:
    use_sim_time: True
    smoother_plugins: ["Simple"]
    Simple:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 0.1
      w_smooth: 0.3
      w_data: 0.2
      do_refinement: false


#############################################
#               COSTMAPS
#############################################
global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: map
      robot_base_frame: base_link
      rolling_window: true
      width: 20
      height: 20
      resolution: 0.05
      footprint: "[ [0.18, 0.18], [0.18, -0.18], [-0.18, -0.18], [-0.18, 0.18] ]"
      plugins: ["static_layer", "inflation_layer"]

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        footprint_clearing_enabled: true
        restore_cleared_footprint: true 

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        footprint_clearing_enabled: true
        inflation_radius: 0.13  
        cost_scaling_factor: 6.0

      update_frequency: 30.0
      publish_frequency: 30.0


local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: odom
      robot_base_frame: base_link
      rolling_window: true
      width: 5
      height: 5
      resolution: 0.05
      footprint: "[ [0.18, 0.18], [0.18, -0.18], [-0.18, -0.18], [-0.18, 0.18] ]"

      plugins: ["obstacle_layer", "inflation_layer"]

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        footprint_clearing_enabled: true
        observation_sources: "scan"
        scan:
          topic: /scan
          data_type: "LaserScan"
          clearing: true
          marking: true
          max_obstacle_height: 2.0

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        footprint_clearing_enabled: true
        inflation_radius: 0.13
        cost_scaling_factor: 6.0

      update_frequency: 30.0
      publish_frequency: 30.0


#############################################
#            BEHAVIOR SERVER
#############################################
behavior_server:
  ros__parameters:
    use_sim_time: true
    cycle_frequency: 10.0
    global_frame: odom
    robot_base_frame: base_link
    transform_tolerance: 0.1
    behavior_plugins: ["backup", "wait"]
    backup:
      plugin: "nav2_behaviors/BackUp"
      target_z: -0.30    
      speed: 0.15
    wait:
      plugin: "nav2_behaviors/Wait"


#############################################
#          VELOCITY SMOOTHER
#############################################
velocity_smoother:
  ros__parameters:
    use_sim_time: true
    smoothing_frequency: 20.0
    scale_velocities: true
    feedback: "OPEN_LOOP"
    odom_topic: "/odometry/filtered"
    max_velocity: [2.0, 2.0, 3.5]
    max_accel: [2.5, 2.0, 4.0]
    max_decel: [-2.5, -2.0, -4.0]


#############################################
#         ROBOT STATE PUBLISHER
#############################################
robot_state_publisher:
  ros__parameters:
    use_sim_time: True


#############################################
#         WAYPOINT FOLLOWER
#############################################
waypoint_follower:
  ros__parameters:
    use_sim_time: True
    loop_rate: 20
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200


#############################################
#       LIFECYCLE MANAGER
#############################################
lifecycle_manager_navigation:
  ros__parameters:
    use_sim_time: true
    autostart: true
    node_names:
      # - slam_toolbox
      - planner_server
      - controller_server
      - behavior_server
      - smoother_server
      - bt_navigator
      - global_costmap
      - local_costmap
      - velocity_smoother
      - waypoint_follower
