server {
    listen 80;
    server_name localhost;

    location /robot_images/ {
        root /usr/share/nginx/html;
        # Disable caching so Grafana always sees the newest image
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        add_header Expires 0;
        
        # Allow Grafana to fetch images even if it's on a different port (CORS)
        add_header 'Access-Control-Allow-Origin' '*';
        
        autoindex on;
    }
}